//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import UIKit

//MARK: - RouteParametersProtocol

protocol RouteParametersProtocol: class {
    
    associatedtype R: Route
    
    var coordinator: AnyCoordinator<R> { get set }
}
