//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import UIKit

// MARK: - StyleProtocol extensions

extension ___VARIABLE_MODULE1UPPER___ViewController: StyleProtocol {

}

// MARK: - Specific style animation extensions

extension ___VARIABLE_MODULE1UPPER___ViewController {

}
