//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import Foundation

// MARK: - ___VARIABLE_MODULE2UPPER___Interactor

final class ___VARIABLE_MODULE2UPPER___Interactor {

    // MARK: Properties

}

// MARK: - ___VARIABLE_MODULE2UPPER___PresenterInteractor Extensions

extension ___VARIABLE_MODULE2UPPER___Interactor: ___VARIABLE_MODULE2UPPER___InteractorProtocol {

}
