//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import Foundation
import RxCoordinator

// MARK: - View protocol

protocol ___VARIABLE_productName___ViewProtocol: class {

}

// MARK: - Presenter protocol

protocol ___VARIABLE_productName___PresenterProtocol: class {

}

// MARK: - Interactor protocol

protocol ___VARIABLE_productName___InteractorProtocol: class {
    
}

// MARK: - Wireframe protocol

protocol ___VARIABLE_productName___WireframeProtocol: class {
    // TODO: Give route name
    func navigate(to option: <#RouteName#>)
}






