//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the BVIPER OpenFleet Xcode Templates.
//

import XCTest
import Nimble
@testable import ___PROJECTNAME___

// MARK: - ___VARIABLE_moduleName___PresenterTests

class ___VARIABLE_moduleName___PresenterTests: XCTestCase {

    // MARK: Test properties

    var presenter:          ___VARIABLE_moduleName___Presenter!

    var mockInteractor:     Mock___VARIABLE_moduleName___Interactor!
    var mockWireframe:      Mock___VARIABLE_moduleName___Wireframe!
    var mockUserInterface:  Mock___VARIABLE_moduleName___ViewController!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()

        mockInteractor      = Mock___VARIABLE_moduleName___Interactor()
        mockWireframe       = Mock___VARIABLE_moduleName___Wireframe()
        mockUserInterface   = Mock___VARIABLE_moduleName___ViewController()

        presenter = ___VARIABLE_moduleName___Presenter()
        presenter.userInterface = mockUserInterface
        presenter.interactor    = mockInteractor
        presenter.wireframe     = mockWireframe
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: show___VARIABLE_moduleName___Module tests

    func test_show___VARIABLE_moduleName___Module() {

        // When
        presenter.show___VARIABLE_moduleName___Module()

        // Then
        expect(self.mockWireframe.show___VARIABLE_moduleName___ModuleCalled) == true
    }

    // MARK: - ___VARIABLE_moduleName___ModuleProtocol implementation
    // MARK: doSomething tests

//    func test_doSomething() {
//        // Given
//
//        // When
//
//        // Then
//    }

    // MARK: - ___VARIABLE_moduleName___InteractorDelegate implementation
    // MARK: interactorDidSomething tests

//    func test_interactorDidSomething() {
//        // Given
//
//        // When
//
//        // Then
//    }

}
