//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import UIKit

// MARK: - ___VARIABLE_moduleName___ViewController

final class ___VARIABLE_moduleName___ViewController: UIViewController {

    // MARK: IBOutlets

    // MARK: Properties

    var presenter: ___VARIABLE_moduleName___PresenterProtocol?
    
    // MARK: Lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        initializeStyle()
    }

    // MARK: IBActions

}

// MARK: - ___VARIABLE_moduleName___ViewProtocol extensions

extension ___VARIABLE_moduleName___ViewController: ___VARIABLE_moduleName___ViewProtocol {

}
