//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the BVIPER OpenFleet Xcode Templates.
//

import UIKit

// MARK: - ___VARIABLE_moduleName___Wireframe

final class ___VARIABLE_moduleName___Wireframe: BaseWireframeProtocol {

    // MARK: Properties

    weak var viewController: ___VARIABLE_moduleName___ViewController?

    // MARK: Create module
    
    static func createModule(with parameters: ___VARIABLE_moduleName___.Parameters) -> ___VARIABLE_moduleName___ViewController {
        
        let view = StoryboardScene.___VARIABLE_moduleName___.___VARIABLE_moduleName___ViewController.instantiate()
        let interactor = ___VARIABLE_moduleName___Interactor()
        let wireframe = ___VARIABLE_moduleName___Wireframe()
        let presenter = ___VARIABLE_moduleName___Presenter(interface: view, interactor: interactor, wireframe: wireframe, parameters: parameters)
        view.presenter = presenter
        interactor.presenter = presenter
        wireframe.viewController = view
        
        return view
    }
}

// MARK: - ___VARIABLE_moduleName___WireframeProtocol implementation

extension ___VARIABLE_moduleName___Wireframe: ___VARIABLE_moduleName___WireframeProtocol {
    
    func navigate(to option: ___VARIABLE_moduleName___.NavigationOption) {
    }
}
