//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import Foundation
import RxCoordinator

// MARK: - ___VARIABLE_moduleName___

enum ___VARIABLE_moduleName___ {
    
    // MARK: - Module Parameters
    
    struct Parameters {

    }
    
    // MARK: - Models Formatter
    
    enum Formatter {
        
    }

    // MARK: - Internal Models
    
    enum Something {
        
        struct ViewModel {
        }
        
        struct Request {
        }
        
        struct Response {
        }
    }
}
