//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import XCTest
@testable import ___PROJECTNAME___

// MARK: - Mock___VARIABLE_moduleName___ViewController

class Mock___VARIABLE_moduleName___ViewController {

    // MARK: ___VARIABLE_moduleName___PresenterProtocol test properties

//    var displaySomethingCalled = false

}

// MARK: - ___VARIABLE_moduleName___ViewProtocol extensions

extension Mock___VARIABLE_moduleName___ViewController: ___VARIABLE_moduleName___PresenterProtocol {
    
    //    func displaySomething() {
    //        displaySomethingCalled = true
    //    }
}
