//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import XCTest
@testable import ___PROJECTNAME___

// MARK: - Mock___VARIABLE_moduleName___Presenter

final class Mock___VARIABLE_moduleName___Presenter {

    // MARK: ___VARIABLE_moduleName___PresenterProtocol test properties

    //var doSomethingCalled = false

}

// MARK: - ___VARIABLE_moduleName___PresenterViewProtocol extensions

extension Mock___VARIABLE_moduleName___PresenterProtocol: ___VARIABLE_moduleName___PresenterProtocol {
    
    //    func soSomething() {
    //        doSomethingCalled = true
    //    }
}
