//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import XCTest
@testable import ___PROJECTNAME___

// MARK: - Mock___VARIABLE_moduleName___Presenter

final class Mock___VARIABLE_moduleName___Presenter {

    // MARK: ___VARIABLE_moduleName___PresenterViewProtocol test properties

    
    //var doSomethingCalled = false
    
    // MARK: ___VARIABLE_moduleName___InteractorProtocol test properties

    //var doSomethingCalled = false
}

// MARK: - ___VARIABLE_moduleName___PresenterViewProtocol extensions

extension Mock___VARIABLE_moduleName___PresenterViewProtocol: ___VARIABLE_moduleName___PresenterViewProtocol {
    
    //    func soSomething() {
    //        doSomethingCalled = true
    //    }
}

// MARK: - ___VARIABLE_moduleName___InteractorProtocol extensions

extension Mock___VARIABLE_moduleName___PresenterInteractorProtocol: ___VARIABLE_moduleName___PresenterInteractorProtocol {
    
    //    func soSomething() {
    //        doSomethingCalled = true
    //    }
}
