//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import XCTest
@testable import ___PROJECTNAME___

// MARK: - Mock___VARIABLE_moduleName___Interactor

class Mock___VARIABLE_moduleName___Interactor {

    // MARK: ___VARIABLE_moduleName___PresenterInteractor test properties

    //var doSomethingCalled = false

}

// MARK: - ___VARIABLE_moduleName___PresenterInteractor implementation

extension Mock___VARIABLE_moduleName___Interactor: ___VARIABLE_moduleName___InteractorProtocol {

//    func soSomething() {
//        doSomethingCalled = true
//    }

}
