//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the BVIPER OpenFleet Xcode Templates.
//

import XCTest
@testable import ___PROJECTNAME___

// MARK: - ___VARIABLE_moduleName___WireframeProtocol

class Mock___VARIABLE_moduleName___Wireframe {

    // MARK: ___VARIABLE_moduleName___WireframeProtocol test properties

    var createModule___VARIABLE_moduleName___Called  = false

}

// MARK: - BaseWireframeProtocol implementation

extension Mock___VARIABLE_moduleName___Wireframe: BaseWireframeProtocol {

    static func createModule() -> ___VARIABLE_moduleName___ViewController {
        createModule___VARIABLE_moduleName___Called = true
        return ___VARIABLE_moduleName___ViewController()
    }
    
    static func createModule(with parameters: ___VARIABLE_moduleName___.Parameters) -> ___VARIABLE_moduleName___ViewController {
        createModule___VARIABLE_moduleName___Called = true
        return ___VARIABLE_moduleName___ViewController()
    }

}

// MARK: - ___VARIABLE_moduleName___WireframeProtocol implementation

extension Mock___VARIABLE_moduleName___Wireframe: ___VARIABLE_moduleName___WireframeProtocol {
    
    func navigate(to option: ___VARIABLE_moduleName___.NavigationOption) {
        
    }
    
}
