//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import Foundation
import RxCoordinator

// MARK: - AppCoordinator

final class ___VARIABLE_MODULE1___Coordinator {
    
    // MARK: Propreties
    
    typealias CoordinatorRoute = ___ROUTE___Route
    
    public var context: UIViewController!
    public var navigationController: UINavigationController
    public var rootViewController: UIViewController {
        get {
            return self.navigationController
        }
    }
    
    // MARK: Initializer
    
    public init(initiale route: ___ROUTE___Route) {
        self.navigationController = UINavigationController()
        transition(to: route)
    }
}

// MARK: - Coordinator extensions

extension ___VARIABLE_MODULE1___Coordinator: Coordinator {
    
    open func presented(from presentable: Presentable?) {
        
    }
    
}
