//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import UIKit
import RxCoordinator

//MARK: - BaseWireframeProtocol

protocol BaseWireframeProtocol: class {
    
    associatedtype V: UIViewController
    associatedtype U
    associatedtype R: Route
    
    var coordinator: AnyCoordinator<R>? { get set }
    
    static func createModule(with parameters: U, coordinator: AnyCoordinator<R>) -> V
}

//MARK: - BaseWireframeProtocol extensions

extension BaseWireframeProtocol {
    
    static func createModule(with parameters: U, coordinator: AnyCoordinator<R>) -> V {
        fatalError("Implementation pending...")
    }
}

//MARK: - BaseWireframeProtocol extensions

extension BaseWireframeProtocol {
    
    var appDelegate: AppDelegate? {
        return UIApplication.shared.delegate as? AppDelegate
    }
    
    var window: UIWindow? {
        return appDelegate?.window
    }
    
    var rootViewController: UIViewController? {
        return window?.rootViewController
    }
}
