//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import UIKit

// MARK: - DeviceHelper

public enum HelperDevice {
    
    /// The screen sizes for all available iPhone and iPad's
    ///
    /// - iPhone4:      3.5 inch iPhone (4, 4S)
    /// - iPhone5:      4.0 inch iPhone (5, 5S, 5C)
    /// - iPhone6:      4.7 inch iPhone (6, 7, 8)
    /// - iPhone6Plus:  5.5 inch iPhone (6+, 7+, 8+)
    /// - iPhoneX:      5.8 inch iPhone
    /// - iPad9_7:      9.7 inch iPad
    /// - iPad10_5:     10.5 inch iPad
    /// - iPad12_9:     12.9 inch iPad
    public enum ModelDevice: Int {
        /// 3.5 inch iPhone (4, 4S)
        case iPhone4
        
        /// 4.0 inch iPhone (5, 5S, 5C)
        case iPhone5
        
        /// 4.7 inch iPhone (6, 7, 8)
        case iPhone6
        
        /// 5.5 inch iPhone (6+, 7+, 8+)
        case iPhone6Plus
        
        /// 5.8 inch iPhone
        case iPhoneX
        
        /// 9.7 inch iPad
        case iPad9
        
        /// 10.5 inch iPad
        case iPad10
        
        /// 12.9 inch iPad
        case iPad12
    }
    
    /// Current device model
    public static var model: ModelDevice {
        switch screenHeight > screenWidth ? screenHeight : screenWidth {
        case 480:   return .iPhone4
        case 568:   return .iPhone5
        case 667:   return .iPhone6
        case 736:   return .iPhone6Plus
        case 812:   return .iPhoneX
        case 1024:  return .iPad9
        case 1112:  return .iPad10
        default:    return .iPad12
        }
    }
    
    /// Current device screenHeight
    public static var screenSize: CGRect {
        return UIScreen.main.bounds
    }
    
    /// Current device screenHeight
    public static var screenHeight: CGFloat {
        return UIScreen.main.bounds.size.height
    }
    
    /// Current device screenWidth
    public static var screenWidth: CGFloat {
        return UIScreen.main.bounds.size.width
    }
}


// MARK: - Comparable ModelDevice implementation

private extension DeviceHelper.ModelDevice: Comparable {
    static func <(lhs: DeviceHelper.ModelDevice, rhs: DeviceHelper.ModelDevice) -> Bool {
        return lhs.rawValue < rhs.rawValue
    }
}
