//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import Foundation
import UIKit

// MARK: - StyleProtocol

protocol StyleProtocol {
    
    /// Call this in viewDidLoad
    func initializeStyle()
    
    /// Don't call the function, initializeStyle will do it for you
    func initializeCommonStyle()
    func initializeIPhone4Style()
    func initializeIPhone5Style()
    func initializeIPhone6Style()
    func initializeIPhone6PlusStyle()
    func initializeIPhoneXStyle()
}

// MARK: StyleProtocol implementation

extension StyleProtocol {
    
    // MARK: Variations
    
    func initializeStyle() {
        initializeCommonStyle()
        switch HelperDevice.model {
        case .iPhone4:      initializeIPhone4Style()
        case .iPhone5:      initializeIPhone5Style()
        case .iPhone6:      initializeIPhone6Style()
        case .iPhone6Plus:  initializeIPhone6PlusStyle()
        case .iPhoneX:      initializeIPhoneXStyle()
        default: break
        }
    }
    
    func initializeCommonStyle()        {}
    func initializeIPhone4Style()       {}
    func initializeIPhone5Style()       {}
    func initializeIPhone6Style()       {}
    func initializeIPhone6PlusStyle()   {}
    func initializeIPhoneXStyle()       {}
}
