//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import Foundation
import RxCoordinator

// MARK: - ___VARIABLE_moduleName___Route

enum ___VARIABLE_moduleName___Route: Route {
    case <#First module name#>
    case <#second module name#>
    
    func prepareTransition(coordinator: AnyCoordinator<___VARIABLE_moduleName___Route>) -> NavigationTransition {
        switch self {
        case .<#First module name#>:
            /*
             case test(let outputParameters)
             let param = Test.Parameters(coordinator: coordinator, parameters: outputParameters)
             let vc = TestWireframe.createModule(with: param)
             return .push(vc)
            */
        case .<#second module name#>:
            return .dismiss()
        }
    }
}
