//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

import Foundation

// MARK: - ___VARIABLE_moduleName___Interactor

final class ___VARIABLE_moduleName___Interactor {

    // MARK: Properties
    
    weak var presenter: ___VARIABLE_moduleName___PresenterInteractorProtocol?

}

// MARK: - ___VARIABLE_moduleName___PresenterInteractor Extensions

extension ___VARIABLE_moduleName___Interactor: ___VARIABLE_moduleName___InteractorProtocol {

}
