//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Stephan Yannick @YannickSteph
//

// MARK: - BaseWireframeProtocol

//MARK: - BaseWireframeProtocol

protocol BaseWireframeProtocol: class {
    
    associatedtype V: UIViewController
    associatedtype U
    associatedtype R: Route
    
    static func createModule(with parameters: U, coordinator: AnyCoordinator<R>) -> V
}

//MARK: - BaseWireframeProtocol extensions

extension BaseWireframeProtocol {
    
    static func createModule(with parameters: U, coordinator: AnyCoordinator<R>) -> V {
        fatalError("Implementation pending...")
    }
}
